export default {
  // 用户
  USER_LOGIN: 'USER_LOGIN',

  //商品
  LOAD_GOODS: 'LOAD_GOODS',
  LOAD_GOODS_SUCCESS: 'LOAD_GOODS_SUCCESS',
  LOAD_GOODS_FAILED: 'LOAD_GOODS_FAILED',

  REFRESH_GOODS: 'REFRESH_GOODS',
  REFRESH_GOODS_SUCCESS: 'REFRESH_GOODS_SUCCESS',
  REFRESH_GOODS_FAILED: 'REFRESH_GOODS_FAILED',
};
